blank_issues_enabled: false
contact_links:
  - name: Professional diagnostic request
    url: https://github.com/ztxdev/software-diagnostic-checklist/issues/new/choose
    about: For broader software/system diagnostic discussions
